In [7]:
with open('input.txt','r',encoding='utf-8') as f:
    text = f.read()

In [8]:
print("Length of the dataset:", len(text))
print("First 100 characters of the dataset:")
print(text[:1000])

Length of the dataset: 38148451
First 100 characters of the dataset:
from rest_framework_gis import serializers
from rest_framework import serializers as s

from .models import (
    Artificialisee2015to2018,
    Artificielle2018,
    CommunesSybarval,
    CouvertureSol,
    EnveloppeUrbaine2018,
    Ocsge,
    Renaturee2018to2015,
    Sybarval,
    Voirie2018,
    ZonesBaties2018,
    UsageSol,
)


def get_label(code="", label=""):
    if code is None:
        code = "-"
    if label is None:
        label = "inconnu"
    return f"{code} {label[:30]}"


class Artificialisee2015to2018Serializer(serializers.GeoFeatureModelSerializer):
    usage_2015 = s.SerializerMethodField()
    usage_2018 = s.SerializerMethodField()
    couverture_2015 = s.SerializerMethodField()
    couverture_2018 = s.SerializerMethodField()

    def get_usage_2015(self, obj):
        return get_label(code=obj.us_2015, label=obj.us_2015_label)

    def get_usage_2018(self, obj):
        return get_label(code=obj.us

In [9]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print("All the unique characters:", ''.join(chars))
print(f"Vocab size: {vocab_size}")

All the unique characters:	
 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~ ¡£¨©ª«°±²´µ·º»ÀÁÃÄÅÇÉËÍÎÓÕÖ×ØÚÜÞßàáâãäåæçèéêëìíîïðñòóôõöøùúüýþāăąćĉČčĐđēėęěĞğĩīįİıľŁłńňŋőœŘřśŞşŠšţťũūűųŹźżžƏơưǎǐǔșțɑɒɔəɛɜɣɤɪɯɲʂʃʈʊʌʐʒʔʤʧʰʳʷˈˌ˜̠̃̆̈̊͡ΆΈΑΒΓΔΕΛΜΟΠΣΤΥΦΩάέήίαβγδεζηθικλμνξοπρςστυφχωόύώІАБВГДЕЗИЙКЛМНОПРСТУФЦЧЫЭЯабвгдежзийклмнопрстуфхцчшщъыьэюяёєіїўԱԾՄՆՍաբգեէըթիլխծկհղճմյնշոչպջսվտրցւָֹּׁאבגדהוזחטיכלםמןנסעפץצקרשתءآأؤإئابةتثجحخدذرزسشصضطظعغفقكلمنهوىئ٤ٹپچڈڑژکگںھہیےँंअआइउएओऔकखगचजटठडणतथदधनपफबभमयरलवशषसह़ािीुूेैोौ्ঁংঃঅআইঈউঊঋএঐওঔকখগঘঙচছজঝঞটঠডঢণতথদধনপফবভমযরলশষসহ়ািীুূৃেৈোৌ্ৎৗড়ঢ়য়০১২৩৪৫৬৭৮৯ৰஅஆஇஎஒஓகஙசஞடணதநனபமயரறலளழவாிீுூெேைொோ்ంఅఆఇఉఓఔకఖగఘచజటడతదధనపఫబమయరలవశషసహాిీుూృెేైొో్ౖกขคงฉดตนบมยวสอัาำิีไ่้აბგდევზთიკლმნოპრსტუფქღყშჩცძწჭხᚠᚻᛇᵀᵉạảấầẩẫậắằẳẵặẹẻẽếềểễệỉịọỏốồổỗộớờỞởỡợụủứừửữựỳỵỷỹ​‌‐–—‘’“”„•…‰′›‼⁴ₖ€℃ℓ←↑→↓↩⇒⇦⇧⇨⇩∀∂∃∈−√∧∨∫≠≤≥⊃⊛⋅⌚⎢─━│┎┒└┘┚├┲┵┻═║╔╗╚╝╠╯█▉▌░□▶●☁☝♥⚖⚙⚠⚡✅✉✓✔✘✨✪✿❌❎❓❔❯➖➜➡⟢⟩⟫⟳⬅⬆⬇　、。》「」【】〘〙〜あいうえおかがきぎくぐけげこごさしじすずせそぞただちっつてでとどなにねのはばびへべほまみむめもゃやよらりるれろわをんァアィイウェエォオカガキギクグケゲコゴサザシジスズセ

In [10]:
import tiktoken
enc = tiktoken.get_encoding("o200k_base")
print(f"Tokenizer loaded. Vocabulary size: {enc.n_vocab}")


Tokenizer loaded. Vocabulary size: 200019


In [11]:
import torch
import numpy as np

# --- Configuration ---
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?
# -----------------------

# 1. Load data from .bin files
# We load the entire file into a numpy array
# We MUST use the same dtype we saved it with (np.uint32)
train_data_np = np.fromfile('/Users/samemmanuel/Documents/MS/Project Works /P-Transformer model/train.bin', dtype=np.uint32)
val_data_np = np.fromfile('/Users/samemmanuel/Documents/MS/Project Works /P-Transformer model/val.bin', dtype=np.uint32)

# 2. Convert to PyTorch tensors
# We convert to int64 (torch.long) as this is what nn.Embedding expects
train_data = torch.from_numpy(train_data_np.astype(np.int64))
val_data = torch.from_numpy(val_data_np.astype(np.int64))

print(f"Loaded train data with {len(train_data)} tokens.")
print(f"Loaded val data with {len(val_data)} tokens.")

# 3. The get_batch function (your code)
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    # generate random starting indices for each sequence in the batch
    ix = torch.randint(len(data) - block_size, (batch_size,))
    
    # stack the sequences into a batch
    # x is the input sequence
    x = torch.stack([data[i:i+block_size] for i in ix])
    # y is the target sequence (shifted by one)
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

# 4. The test run (your code)
xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

# 5. The loop to show how context builds (your code)
for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

Loaded train data with 8535591 tokens.
Loaded val data with 948400 tokens.
inputs:
torch.Size([4, 8])
tensor([[  2932, 121512,  34553,     11,   2787,    382,  11351,   2241],
        [   352,   2616,  10289,  65762,   5874,    271,  13310,   1950],
        [   395, 101899,    350,     49,  66991,  19853,   6294,    271],
        [ 45212,  13575,  16879,   2402,   2697,    522,   1303,   2408]])
targets:
torch.Size([4, 8])
tensor([[121512,  34553,     11,   2787,    382,  11351,   2241,     65],
        [  2616,  10289,  65762,   5874,    271,  13310,   1950,    706],
        [101899,    350,     49,  66991,  19853,   6294,    271,    712],
        [ 13575,  16879,   2402,   2697,    522,   1303,   2408,  83412]])
----
when input is [2932] the target: 121512
when input is [2932, 121512] the target: 34553
when input is [2932, 121512, 34553] the target: 11
when input is [2932, 121512, 34553, 11] the target: 2787
when input is [2932, 121512, 34553, 11, 2787] the target: 382
when input is 

In [12]:
print(xb)

tensor([[  2932, 121512,  34553,     11,   2787,    382,  11351,   2241],
        [   352,   2616,  10289,  65762,   5874,    271,  13310,   1950],
        [   395, 101899,    350,     49,  66991,  19853,   6294,    271],
        [ 45212,  13575,  16879,   2402,   2697,    522,   1303,   2408]])


In [14]:
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(1337)



class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        # token embeddings: maps each token id to a vector of logits over the vocab
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        logits = self.token_embedding_table(idx)  # (B,T,C)
        loss = None
        if targets is not None:
            B, T, C = logits.shape
            logits_flat = logits.view(B * T, C)
            targets_flat = targets.view(B * T)
            loss = F.cross_entropy(logits_flat, targets_flat)
        return logits, loss

m = BigramLanguageModel(model_vocab_size)
logits, loss = m(xb, yb)
print('logits.shape =', logits.shape)
print('loss =', loss)

: 